_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 2048
entropy:
    value: -2
episodes:
    value: 10000
lr_actor:
    value: 0.0003
lr_critic:
    value: 0.0003
nn_dims:
    value: 512
temperature:
    value: 0.3
